version: "3"

services:
  redis:
    image: "redis"
    container_name: "support_redis"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:15.2"
    container_name: "support_db"
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: "Dockerfile"

    command: "gunicorn src.config.wsgi:application --bind 0.0.0.0:8000"

    image: "support_app"
    container_name: "support_app"
    env_file: ".env"
    depends_on:
      - "postgres"
    volumes:
      - "static_volume:/app/staticfiles"
      - ".:/app/"
    #ports:
    #  - "8000:8000"
    expose:
      - "8000"

  nginx:
    build: ./nginx
    ports:
      - "1300:80"
    volumes:
      - "static_volume:/app/staticfiles"
    depends_on:
      - "app"
    restart: "on-failure"


volumes:
  pg_data: {}
  static_volume:
